name: Generate Graph

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: 4.1

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages("ggplot2)'

      - name: Run inflation.R and save graph as artifact
        run: |
          Rscript inflation.R
          mv graph.png $GITHUB_WORKSPACE/graph.png
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: graph
          path: ${{ github.workspace }}/graph.png
